update

diff --git a/bcx b/bcx
--- a/bcx
+++ b/bcx
@@ -1,12 +1,10 @@
-#!/usr/bin/bash
-#shellcheck disable=SC2317 #SC2034  # Some metadata variables may be unused
+#!/bin/bash
+#shellcheck disable=SC2317,SC2155
 # bcx - terminal calculator for floating point expressions
 set -euo pipefail
 shopt -s inherit_errexit shift_verbose extglob nullglob
 
-##
-## INITIALIZATION
-##
+## INITIALIZATION ##
 
 # Script metadata
 declare -r VERSION='1.0.0' # 2025-10-20
@@ -19,9 +17,7 @@ declare -i err=0 is_terminal=0
 declare -r HISTFILE="$HOME"/.bcx_history
 declare -ri HISTSIZE=1000 HISTFILESIZE=2000
 
-##
-## FUNCTIONS
-##
+## FUNCTIONS ##
 
 cleanup() {
   local -i exit_code=${1:-$?}
@@ -73,13 +69,10 @@ interactive_loop() {
 
   local -- expr
   local -i read_rc
-  while :; do
+  while ((1)); do
     >&2 read -e -r -p '> ' expr
     read_rc=$?
-    if ((read_rc != 0)); then
-      # read failed - Ctrl-D (EOF)
-      break
-    fi
+    ((read_rc == 0)) || break # read failed - Ctrl-D (EOF)
     [[ -n $expr ]] || break
     history -s "$expr"
     evaluate_expression "$expr" || :
@@ -123,19 +116,16 @@ Then:
   ? 23x42         # can use x for * on command line
   ? 23 x 42       # with spaces
 EOT
-  exit "${1:-0}"
 }
 
-##
-## EXECUTION
-##
+## EXECUTION ##
 
 # Simple Argument parsing
-[[ ${1:-} == '-h' || ${1:-} == '--help' ]] && show_help 0
+[[ ${1:-} == '-h' || ${1:-} == '--help' ]] && { show_help; exit 0; }
 [[ ${1:-} == '-V' || ${1:-} == '--version' ]] && { echo "bcx $VERSION"; exit 0; }
 
 # Locate bc command
-declare -r BC=$(command -v bc) || { >&2 echo 'bcx: ✗ bc not found'; exit 1; }
+declare -r BC=$(command -v bc) || { >&2 echo "bcx: ✗ 'bc' not found"; exit 1; }
 
 # Setup error file with mktemp
 declare -r errfile=$(mktemp -t bcx-error.XXXXXX) || { >&2 echo 'bcx: ✗ Cannot create temp file'; exit 1; }
@@ -152,20 +142,20 @@ readonly is_terminal
 if (($#)); then
   # Process and evaluate initial expression
   expression=$(process_expression "$@")
-  ((is_terminal)) && {
+  ((is_terminal==0)) || {
     expression=${expression//x/*} # convert x to * if is_terminal
     >&2 echo "> $expression"
   }
   evaluate_expression "$expression" || err=1
 else
   # No expression provided - show help in non-terminal mode
-  ((is_terminal)) || >&2 show_help 1
+  ((is_terminal)) || { >&2 show_help; exit 1; }
 fi
 
 # Interactive REPL if terminal
 if ((is_terminal)); then
   setup_history
-  (($#)) && history -s "$expression"  # Add initial expression to history if provided
+  (($#==0)) || history -s "$expression"  # Add initial expression to history if provided
   interactive_loop
   set +o history  # Disable history to prevent script commands from being saved
 fi
